"use client";

import { TEAM_BADGES } from "@/lib/team-badges";

function monogram(team: string): string {
  return (
    team
      .split(",")[0]
      .split(/[\s-]+/)
      .slice(0, 3)
      .map((w) => w[0])
      .join("") || "?"
  );
}

/**
 * SofaScore team badge (W10d). Uses the pre-resolved club -> badge map
 * generated by src/fetch_logos.py; falls back to the CSS monogram crest
 * for clubs with no resolved badge.
 */
export function TeamBadge({
  team,
  size = 44,
  className = "",
}: {
  team: string;
  size?: number;
  className?: string;
}) {
  const club = team.split(",")[0];
  const src = TEAM_BADGES[club];

  if (!src) {
    return (
      <span
        aria-hidden
        title={club}
        style={{ width: size, height: size }}
        className={`flex shrink-0 items-center justify-center rounded-full border border-line-strong bg-panel-2 font-display text-sm font-semibold uppercase text-ink-dim ${className}`}
      >
        {monogram(team)}
      </span>
    );
  }

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={`${club} badge`}
      title={club}
      width={size}
      height={size}
      loading="lazy"
      className={`shrink-0 bg-panel-2 object-contain ${className}`}
    />
  );
}
